# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 01:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.PositiveSmallIntegerField(default=0, help_text='Lot | Lote', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('location', models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, unique=True)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Rate | Tarifa', max_digits=6)),
                ('description', models.TextField(blank=True, help_text='Description | Descripción', null=True)),
                ('observation', models.TextField(blank=True, help_text='Observation | Observación', null=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Rate',
                'db_table': 'rates',
                'verbose_name_plural': 'Rates',
                'ordering': ('lot', 'location'),
            },
        ),
    ]
