# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 01:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(default=datetime.datetime(2018, 6, 18, 20, 38, 28, 712022), help_text='Fecha programada | Fecha programada')),
                ('active', models.BooleanField(default=True, help_text='Active | Activo')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('rate', models.OneToOneField(help_text='Menu | Menú', on_delete=django.db.models.deletion.CASCADE, to='rates.Rate')),
                ('user', models.OneToOneField(help_text='Menu | Menú', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'db_table': 'task',
                'verbose_name_plural': 'Task',
                'ordering': ('user', 'rate'),
            },
        ),
    ]
