# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 01:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rate',
            field=models.ForeignKey(help_text='Menu | Menú', on_delete=django.db.models.deletion.CASCADE, to='rates.Rate'),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 18, 20, 51, 54, 104754), help_text='Fecha programada | Fecha programada'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(help_text='Menu | Menú', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
