# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 01:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180618_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scheduled_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 20, 53, 13, 771778), help_text='Fecha programada | Fecha programada'),
        ),
    ]
