# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180618_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='scheduled_date',
        ),
    ]
