# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 05:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hour',
            field=models.PositiveSmallIntegerField(default=0, help_text='Hour(s) | Hora(s)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
